const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('bmw', {
  setWorkspaceMode: (mode:string) => ipcRenderer.invoke('workspace-mode',mode),
  onWorkspace: (listener) => ipcRenderer.on('video-workspace-state',(_event,value)=>listener(value)),
  openProductPanel: (id:string) => ipcRenderer.invoke('product-panel-open',id),
  productInfo: () => ipcRenderer.invoke('product-info'),
  browser: (request) => ipcRenderer.invoke('browser-command', request),
  setAgentControl: (enabled) => ipcRenderer.invoke('permission-agent-control', enabled),
  toggleAgent: (visible) => ipcRenderer.invoke('agent-panel', visible),
  setAgentWidth: (width) => ipcRenderer.invoke('agent-width', width),
  layoutSettings: () => ipcRenderer.invoke('layout-settings'),
  toolbarPanel: (visible: boolean) => ipcRenderer.invoke('toolbar-panel', visible),
  layoutPanel: (visible) => ipcRenderer.invoke('layout-panel', visible),
  configureLayout: (input) => ipcRenderer.invoke('layout-configure', input),
  setLayoutFullscreen: (enabled) => ipcRenderer.invoke('layout-fullscreen', enabled),
  setSessionContinuity: (enabled) => ipcRenderer.invoke('session-continuity', enabled),
  globalSettings: () => ipcRenderer.invoke('global-settings'),
  globalSettingsPanel: (visible) => ipcRenderer.invoke('global-settings-panel', visible),
  updateGlobalSettings: (input) => ipcRenderer.invoke('global-settings-update', input),
  restartApplication: () => ipcRenderer.invoke('application-restart'),
  openAgentAdvancedSettings: () => ipcRenderer.invoke('agent-advanced-settings-open'),
  sessionPanel: (visible) => ipcRenderer.invoke('session-panel', visible),
  listAgentSessions: (query) => ipcRenderer.invoke('agent-session-list', query),
  createAgentSession: () => ipcRenderer.invoke('agent-session-create'),
  selectAgentSession: (sessionId) => ipcRenderer.invoke('agent-session-select', sessionId),
  renameAgentSession: (sessionId, title) => ipcRenderer.invoke('agent-session-rename', sessionId, title),
  forkAgentSession: (sessionId) => ipcRenderer.invoke('agent-session-fork', sessionId),
  archiveAgentSession: (sessionId) => ipcRenderer.invoke('agent-session-archive', sessionId),
  moveAgentSession: (sessionId, direction) => ipcRenderer.invoke('agent-session-move', sessionId, direction),
  scheduledTaskPanel: (visible) => ipcRenderer.invoke('scheduled-task-panel', visible),
  scheduledTasks: () => ipcRenderer.invoke('scheduled-task-list'),
  updateScheduledTask: (taskId, input) => ipcRenderer.invoke('scheduled-task-update', taskId, input),
  removeScheduledTask: (taskId) => ipcRenderer.invoke('scheduled-task-remove', taskId),
  runScheduledTask: (taskId) => ipcRenderer.invoke('scheduled-task-run', taskId),
  projectState: () => ipcRenderer.invoke('project-state'),
  agentContext: () => ipcRenderer.invoke('agent-context-state'),
  onAgentContext: (listener) => ipcRenderer.on('agent-context-state', (_event, value) => listener(value)),
  projectMenu: () => ipcRenderer.invoke('project-menu'),
  projectPanel: (visible) => ipcRenderer.invoke('project-panel', visible),
  createProject: (input) => ipcRenderer.invoke('project-create', input),
  updateProject: (projectId, input) => ipcRenderer.invoke('project-update', projectId, input),
  archiveProject: (projectId) => ipcRenderer.invoke('project-archive', projectId),
  readProjectDocument: (projectId, kind) => ipcRenderer.invoke('project-document-read', projectId, kind),
  writeProjectDocument: (projectId, kind, content) => ipcRenderer.invoke('project-document-write', projectId, kind, content),
  onBrowserState: (listener) => ipcRenderer.on('browser-state', (_event, value) => listener(value)),
  onAgentStatus: (listener) => ipcRenderer.on('agent-status', (_event, value) => listener(value)),
  onAgentLog: (listener) => ipcRenderer.on('agent-log', (_event, value) => listener(value)),
  onMediaStatus: (listener) => ipcRenderer.on('media-status', (_event, value) => listener(value)),
  onLayout: (listener) => ipcRenderer.on('layout-state', (_event, value) => listener(value)),
  onProjectState: (listener) => ipcRenderer.on('project-state', (_event, value) => listener(value)),
  onProjectManagerOpen: (listener) => ipcRenderer.on('project-manager-open', (_event, value) => listener(value)),
  onGlobalSettings: (listener) => ipcRenderer.on('global-settings-state', (_event, value) => listener(value)),
  onScheduledTaskState: (listener) => ipcRenderer.on('scheduled-task-state', (_event, value) => listener(value)),
  onScheduledTaskOpen: (listener) => ipcRenderer.on('scheduled-task-open', (_event, value) => listener(value))
})
