const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('bmw', {
  productInfo: () => ipcRenderer.invoke('product-info'),
  productImportPreview: () => ipcRenderer.invoke('product-import-preview'),
  productImportProject: (input) => ipcRenderer.invoke('product-import-project', input),
  webRuntimeSettings: () => ipcRenderer.invoke('web-runtime-settings'),
  updateWebRuntimeSettings: (input) => ipcRenderer.invoke('web-runtime-settings-update', input),
  browser: (request) => ipcRenderer.invoke('browser-command', request),
  setAgentControl: (enabled) => ipcRenderer.invoke('permission-agent-control', enabled),
  toggleAgent: (visible) => ipcRenderer.invoke('agent-panel', visible),
  setAgentWidth: (width) => ipcRenderer.invoke('agent-width', width),
  layoutSettings: () => ipcRenderer.invoke('layout-settings'),
  layoutPanel: (visible) => ipcRenderer.invoke('layout-panel', visible),
  configureLayout: (input) => ipcRenderer.invoke('layout-configure', input),
  setLayoutFullscreen: (enabled) => ipcRenderer.invoke('layout-fullscreen', enabled),
  setSessionContinuity: (enabled) => ipcRenderer.invoke('session-continuity', enabled),
  globalSettings: () => ipcRenderer.invoke('global-settings'),
  globalSettingsPanel: (visible) => ipcRenderer.invoke('global-settings-panel', visible),
  updateGlobalSettings: (input) => ipcRenderer.invoke('global-settings-update', input),
  restartApplication: () => ipcRenderer.invoke('application-restart'),
  openDshAdvancedSettings: () => ipcRenderer.invoke('dsh-advanced-settings-open'),
  sessionPanel: (visible) => ipcRenderer.invoke('session-panel', visible),
  listDshSessions: (query) => ipcRenderer.invoke('dsh-session-list', query),
  createDshSession: () => ipcRenderer.invoke('dsh-session-create'),
  selectDshSession: (sessionId) => ipcRenderer.invoke('dsh-session-select', sessionId),
  renameDshSession: (sessionId, title) => ipcRenderer.invoke('dsh-session-rename', sessionId, title),
  forkDshSession: (sessionId) => ipcRenderer.invoke('dsh-session-fork', sessionId),
  archiveDshSession: (sessionId) => ipcRenderer.invoke('dsh-session-archive', sessionId),
  moveDshSession: (sessionId, direction) => ipcRenderer.invoke('dsh-session-move', sessionId, direction),
  scheduledTaskPanel: (visible) => ipcRenderer.invoke('scheduled-task-panel', visible),
  scheduledTasks: () => ipcRenderer.invoke('scheduled-task-list'),
  updateScheduledTask: (taskId, input) => ipcRenderer.invoke('scheduled-task-update', taskId, input),
  removeScheduledTask: (taskId) => ipcRenderer.invoke('scheduled-task-remove', taskId),
  runScheduledTask: (taskId) => ipcRenderer.invoke('scheduled-task-run', taskId),
  projectState: () => ipcRenderer.invoke('project-state'),
  projectMenu: () => ipcRenderer.invoke('project-menu'),
  projectPanel: (visible) => ipcRenderer.invoke('project-panel', visible),
  createProject: (input) => ipcRenderer.invoke('project-create', input),
  updateProject: (projectId, input) => ipcRenderer.invoke('project-update', projectId, input),
  archiveProject: (projectId) => ipcRenderer.invoke('project-archive', projectId),
  readProjectDocument: (projectId, kind) => ipcRenderer.invoke('project-document-read', projectId, kind),
  writeProjectDocument: (projectId, kind, content) => ipcRenderer.invoke('project-document-write', projectId, kind, content),
  onBrowserState: (listener) => ipcRenderer.on('browser-state', (_event, value) => listener(value)),
  onDshStatus: (listener) => ipcRenderer.on('dsh-status', (_event, value) => listener(value)),
  onDshLog: (listener) => ipcRenderer.on('dsh-log', (_event, value) => listener(value)),
  onMediaStatus: (listener) => ipcRenderer.on('media-status', (_event, value) => listener(value)),
  onLayout: (listener) => ipcRenderer.on('layout-state', (_event, value) => listener(value)),
  onProjectState: (listener) => ipcRenderer.on('project-state', (_event, value) => listener(value)),
  onProjectManagerOpen: (listener) => ipcRenderer.on('project-manager-open', (_event, value) => listener(value)),
  onGlobalSettings: (listener) => ipcRenderer.on('global-settings-state', (_event, value) => listener(value)),
  onScheduledTaskState: (listener) => ipcRenderer.on('scheduled-task-state', (_event, value) => listener(value)),
  onScheduledTaskOpen: (listener) => ipcRenderer.on('scheduled-task-open', (_event, value) => listener(value))
})
