import {assertArtifactId,finiteNumber,mediaRecord} from '../../media-native/src/media-contract.js'
export interface StudioReferenceObservation {frameIndex:number;description:string;adaptation:string}
export interface StudioReferenceAnalysis {summary:string;observations:StudioReferenceObservation[]}
export interface StudioReferenceFrame {artifactId:string;sha256:string;width:number;height:number;requestedSeconds:number;seconds:number}
export interface StudioReferenceRecord {id:string;sourceArtifactId:string;sourceSha256:string;sourceBytes:number;kind:'image'|'video';width:number;height:number;durationSeconds:number;createdAt:string;revision:number;videoRange?:{startSeconds:number;endSeconds:number};frames:StudioReferenceFrame[];analysis?:StudioReferenceAnalysis;analysisOrigin?:'user'|'agent'}
function closed(v:Record<string,unknown>,keys:readonly string[]):void{if(Object.keys(v).some(k=>!keys.includes(k)))throw new TypeError('Unsupported reference property.')}
function text(raw:unknown,max:number):string{if(typeof raw!=='string'||raw.length>max||/[\u0000-\u0008]/u.test(raw))throw new TypeError('Invalid reference text.');return raw}
function identity(raw:unknown):string{const v=text(raw,80);if(!/^[a-zA-Z0-9-]{1,80}$/u.test(v))throw new TypeError('Invalid reference identity.');return v}
function sha(raw:unknown):string{const v=text(raw,64);if(!/^[a-f0-9]{64}$/u.test(v))throw new TypeError('Invalid reference fingerprint.');return v}
export function assertReferenceAnalysis(raw:unknown):StudioReferenceAnalysis {
 const v=mediaRecord(raw);closed(v,['summary','observations']);const summary=text(v.summary,2000);if(!summary.trim()||!Array.isArray(v.observations)||!v.observations.length||v.observations.length>8)throw new TypeError('Reference analysis needs a summary and one to eight frame observations.')
 const observations=v.observations.map(raw=>{const o=mediaRecord(raw);closed(o,['frameIndex','description','adaptation']);const description=text(o.description,600),adaptation=text(o.adaptation,600);if(!description.trim()||!adaptation.trim())throw new TypeError('Reference observations need concrete content and adaptation.');return {frameIndex:finiteNumber(o.frameIndex,'reference frame',0,7,true),description,adaptation}})
 if(new Set(observations.map(o=>o.frameIndex)).size!==observations.length)throw new TypeError('Duplicate reference frame observation.');return {summary,observations}
}
export function assertReferenceRecords(raw:unknown):StudioReferenceRecord[] {
 if(!Array.isArray(raw)||raw.length>8)throw new TypeError('At most eight prepared references per draft.')
 const records=raw.map(raw=>{const v=mediaRecord(raw);closed(v,['id','sourceArtifactId','sourceSha256','sourceBytes','kind','width','height','durationSeconds','createdAt','revision','frames','videoRange','analysis','analysisOrigin']);if(!['image','video'].includes(String(v.kind))||!Array.isArray(v.frames)||!v.frames.length||v.frames.length>8)throw new TypeError('Invalid prepared reference.')
  const width=finiteNumber(v.width,'reference width',1,16384,true),height=finiteNumber(v.height,'reference height',1,16384,true);if(width*height>16777216)throw new TypeError('Reference source exceeds pixel limit.')
  const durationSeconds=finiteNumber(v.durationSeconds,'reference duration',v.kind==='image'?0:.01,1800);if(v.kind==='image'&&(durationSeconds!==0||v.frames.length!==1))throw new TypeError('An image reference needs one static frame.')
  const range=v.videoRange===undefined?undefined:mediaRecord(v.videoRange);if(range)closed(range,['startSeconds','endSeconds']);const videoRange=v.kind==='video'?{startSeconds:finiteNumber(range?.startSeconds,'reference video start',0,durationSeconds),endSeconds:finiteNumber(range?.endSeconds,'reference video end',0,durationSeconds)}:undefined;if(v.kind==='image'&&range||videoRange&&videoRange.endSeconds<=videoRange.startSeconds)throw new TypeError('Invalid reference video range.')
  const frames=v.frames.map(raw=>{const f=mediaRecord(raw);closed(f,['artifactId','sha256','width','height','requestedSeconds','seconds']);const requestedSeconds=finiteNumber(f.requestedSeconds,'requested reference time',0,durationSeconds),seconds=finiteNumber(f.seconds,'actual reference time',0,requestedSeconds);if(v.kind==='video'&&(requestedSeconds<videoRange!.startSeconds||requestedSeconds>=videoRange!.endSeconds||seconds<videoRange!.startSeconds))throw new TypeError('Reference frame exceeds source endpoint.');return {artifactId:assertArtifactId(f.artifactId),sha256:sha(f.sha256),width:finiteNumber(f.width,'frame width',1,1280,true),height:finiteNumber(f.height,'frame height',1,720,true),requestedSeconds,seconds}})
  if(new Set(frames.map(f=>f.artifactId)).size!==frames.length)throw new TypeError('Duplicate reference frame artifact.')
  const analysis=v.analysis===undefined?undefined:assertReferenceAnalysis(v.analysis);if(analysis&&(!['user','agent'].includes(String(v.analysisOrigin))||analysis.observations.some(o=>o.frameIndex>=frames.length))||!analysis&&v.analysisOrigin!==undefined)throw new TypeError('Invalid reference analysis provenance or frame target.')
  return {id:identity(v.id),sourceArtifactId:assertArtifactId(v.sourceArtifactId),sourceSha256:sha(v.sourceSha256),sourceBytes:finiteNumber(v.sourceBytes,'reference bytes',1,256*1024*1024,true),kind:v.kind as StudioReferenceRecord['kind'],width,height,durationSeconds,createdAt:text(v.createdAt,40),revision:finiteNumber(v.revision,'reference revision',1,1_000_000,true),...(videoRange?{videoRange}:{}),frames,...(analysis?{analysis,analysisOrigin:v.analysisOrigin as 'user'|'agent'}:{})}
 });if(new Set(records.map(r=>r.id)).size!==records.length)throw new TypeError('Duplicate reference record.');return records
}
export function referenceNotes(record:StudioReferenceRecord):string {if(!record.analysis)throw new Error('请先完成参考分析。');return '参考分析（抽样，仍需核对） · '+record.sourceArtifactId+'\n'+record.analysis.summary+'\n'+record.analysis.observations.map(o=>{const f=record.frames[o.frameIndex];return '['+f.seconds.toFixed(2)+' 秒 · '+f.artifactId+'] '+o.description+'\n可借鉴：'+o.adaptation}).join('\n')}
const string={type:'string'},id={type:'string',pattern:'^[a-zA-Z0-9-]{1,80}$'},hash={type:'string',pattern:'^[a-f0-9]{64}$'}
export const referenceAnalysisSchema={type:'object',additionalProperties:false,required:['summary','observations'],properties:{summary:{...string,minLength:1,maxLength:2000},observations:{type:'array',minItems:1,maxItems:8,items:{type:'object',additionalProperties:false,required:['frameIndex','description','adaptation'],properties:{frameIndex:{type:'integer',minimum:0,maximum:7},description:{...string,minLength:1,maxLength:600},adaptation:{...string,minLength:1,maxLength:600}}}}}}
export const referenceRecordsSchema={type:'array',maxItems:8,items:{type:'object',additionalProperties:false,required:['id','sourceArtifactId','sourceSha256','sourceBytes','kind','width','height','durationSeconds','createdAt','revision','frames'],properties:{id,sourceArtifactId:string,sourceSha256:hash,sourceBytes:{type:'integer',minimum:1,maximum:268435456},kind:{enum:['image','video']},width:{type:'integer',minimum:1,maximum:16384},height:{type:'integer',minimum:1,maximum:16384},durationSeconds:{type:'number',minimum:0,maximum:1800},createdAt:{...string,maxLength:40},revision:{type:'integer',minimum:1,maximum:1000000},videoRange:{type:'object',additionalProperties:false,required:['startSeconds','endSeconds'],properties:{startSeconds:{type:'number',minimum:0,maximum:1800},endSeconds:{type:'number',minimum:0,maximum:1800}}},analysis:referenceAnalysisSchema,analysisOrigin:{enum:['user','agent']},frames:{type:'array',minItems:1,maxItems:8,items:{type:'object',additionalProperties:false,required:['artifactId','sha256','width','height','requestedSeconds','seconds'],properties:{artifactId:string,sha256:hash,width:{type:'integer',minimum:1,maximum:1280},height:{type:'integer',minimum:1,maximum:720},requestedSeconds:{type:'number',minimum:0,maximum:1800},seconds:{type:'number',minimum:0,maximum:1800}}}}}}}
