import {assertArtifactId,finiteNumber,mediaRecord} from '../../media-native/src/media-contract.js'
import {speechSha} from '../../media-native/src/speech-contract.js'
import {sceneVisuals} from '../../media-native/src/visual-segments.js'
import type {CaptionCue} from '../../media-native/src/composition-contract.js'
import type {StudioScene} from './studio-contract.js'
export interface SourceSpeechCandidate {sourceArtifactId:string;sourceSha256:string;evidenceArtifactId:string;evidenceSha256:string;durationSeconds:number;segmentIndex:number;createdAt:string}
export interface SourceCaptionBinding {sourceArtifactId:string;sourceSha256:string;segmentIndex:number;clock:string;origin:'user-edited'|'agent-edited'}
function closed(v:Record<string,unknown>,keys:string[]):void{if(Object.keys(v).some(k=>!keys.includes(k)))throw new TypeError('Unsupported source speech property.')}
export function assertSourceCandidate(raw:unknown):SourceSpeechCandidate{const v=mediaRecord(raw);closed(v,['sourceArtifactId','sourceSha256','evidenceArtifactId','evidenceSha256','durationSeconds','segmentIndex','createdAt']);if(typeof v.createdAt!=='string'||v.createdAt.length>40||!Number.isFinite(Date.parse(v.createdAt)))throw new TypeError('Invalid source recognition date.');return {sourceArtifactId:assertArtifactId(v.sourceArtifactId),sourceSha256:speechSha(v.sourceSha256),evidenceArtifactId:assertArtifactId(v.evidenceArtifactId),evidenceSha256:speechSha(v.evidenceSha256),durationSeconds:finiteNumber(v.durationSeconds,'source speech duration',.01,180),segmentIndex:finiteNumber(v.segmentIndex,'source segment',0,7,true),createdAt:v.createdAt}}
export function assertSourceCaptionBinding(raw:unknown):SourceCaptionBinding{const v=mediaRecord(raw);closed(v,['sourceArtifactId','sourceSha256','segmentIndex','clock','origin']);if(typeof v.clock!=='string'||v.clock.length>1000||!['user-edited','agent-edited'].includes(String(v.origin)))throw new TypeError('Invalid source caption binding.');return {sourceArtifactId:assertArtifactId(v.sourceArtifactId),sourceSha256:speechSha(v.sourceSha256),segmentIndex:finiteNumber(v.segmentIndex,'source segment',0,7,true),clock:v.clock,origin:v.origin as SourceCaptionBinding['origin']}}
export function sourceCaptionClock(scene:StudioScene,index:number):string{const visuals=sceneVisuals(scene),v=visuals[index];if(!v?.videoArtifactId)throw new Error('原声字幕需要所选视频片段。');return JSON.stringify({id:v.videoArtifactId,start:v.sourceStartSeconds,rate:v.playbackRate,duration:v.durationSeconds,offset:visuals.slice(0,index).reduce((sum,v)=>sum+v.durationSeconds,0)})}
export function sourceCaptionsStale(scene:StudioScene):boolean{try{return Boolean(scene.sourceCaptionBinding&&scene.sourceCaptionBinding.clock!==sourceCaptionClock(scene,scene.sourceCaptionBinding.segmentIndex))}catch{return true}}
export function assertSourceCues(raw:unknown,duration=180):CaptionCue[]{if(!Array.isArray(raw)||!raw.length||raw.length>100)throw new TypeError('At most one hundred nonempty source cues.');let end=0;return raw.map(raw=>{const v=mediaRecord(raw);closed(v,['startSeconds','endSeconds','text']);const startSeconds=finiteNumber(v.startSeconds,'source cue start',end,duration),endSeconds=finiteNumber(v.endSeconds,'source cue end',startSeconds+.001,duration);if(typeof v.text!=='string'||!v.text.trim()||v.text.length>200||/[\u0000-\u0008]/.test(v.text))throw new TypeError('Invalid source cue text.');end=endSeconds;return {startSeconds,endSeconds,text:v.text}})}
/** Original-source seconds map through the chosen segment, with no narration offset. */
export function projectSourceCues(scene:StudioScene,index:number,cues:CaptionCue[]):CaptionCue[]{const visuals=sceneVisuals(scene),v=visuals[index];sourceCaptionClock(scene,index);const offset=visuals.slice(0,index).reduce((sum,v)=>sum+v.durationSeconds,0),end=v.sourceStartSeconds+v.durationSeconds*v.playbackRate;return cues.flatMap(cue=>{const startSeconds=Math.max(cue.startSeconds,v.sourceStartSeconds),endSeconds=Math.min(cue.endSeconds,end);return endSeconds<=startSeconds?[]:[{text:cue.text,startSeconds:offset+(startSeconds-v.sourceStartSeconds)/v.playbackRate,endSeconds:offset+(endSeconds-v.sourceStartSeconds)/v.playbackRate}]})}
export const sourceCandidateSchema={type:'object',additionalProperties:false,required:['sourceArtifactId','sourceSha256','evidenceArtifactId','evidenceSha256','durationSeconds','segmentIndex','createdAt'],properties:{sourceArtifactId:{type:'string'},sourceSha256:{type:'string',pattern:'^[a-f0-9]{64}$'},evidenceArtifactId:{type:'string'},evidenceSha256:{type:'string',pattern:'^[a-f0-9]{64}$'},durationSeconds:{type:'number',minimum:.01,maximum:180},segmentIndex:{type:'integer',minimum:0,maximum:7},createdAt:{type:'string'}}}
export const sourceCaptionBindingSchema={type:'object',additionalProperties:false,required:['sourceArtifactId','sourceSha256','segmentIndex','clock','origin'],properties:{sourceArtifactId:{type:'string'},sourceSha256:{type:'string',pattern:'^[a-f0-9]{64}$'},segmentIndex:{type:'integer',minimum:0,maximum:7},clock:{type:'string',maxLength:1000},origin:{enum:['user-edited','agent-edited']}}}
