import {assertReferenceRecords,referenceNotes} from '../studio-reference-contract.js'
import type {StudioReferenceRecord} from '../studio-reference-contract.js'
import type {StudioAsset,VideoDraft} from '../studio-contract.js'
interface ReferenceState {projectId:string;sessionId?:string;draft:VideoDraft;disabled:boolean}
interface ReferenceOptions {state:()=>ReferenceState|undefined;command:(request:Record<string,unknown>,owner:{projectId:string;sessionId?:string;draftId:string})=>Promise<Record<string,unknown>>;ask:(referenceId:string)=>Promise<void>;cancel:()=>Promise<void>;bytes:(artifactId:string)=>Promise<Uint8Array>;preview:(asset:StudioAsset,time:number)=>Promise<void>;notify:(text:string)=>void}
/** Keep transport diagnostics in the cause; show recoverable reference actions to users. */
function referenceError(error:unknown):string {
 const message=(error instanceof Error?error.message:String(error)).replace(/^Error invoking remote method '[^']+':(?: Error:)?\s*/u,'')
 if(message.includes('STUDIO_REFERENCE_STALE'))return '参考素材或参考帧已变化，请重新生成参考帧后分析。'
 if(message.includes('STUDIO_REFERENCE_BUDGET'))return '此视频已保存八份参考记录，请在“管理参考记录”中移除不需要的记录后再取帧。'
 if(message.includes('STUDIO_REFERENCE_EDITED'))return '已保留你校正的参考分析，请重新查看后继续。'
 if(message.includes('STUDIO_CONFLICT'))return '视频或制作背景已变化，请重新打开参考分析后继续。'
 return message
}
/** Contextual resource dialog; no model loop, alternate chat or optimistic draft. */
export class StudioReferenceEditor {
 private dialog?:HTMLDialogElement;private key='';private urls:string[]=[];private working=false;private stopRequested=false;private record?:StudioReferenceRecord;private ready=false
 constructor(private options:ReferenceOptions){}
 close():void{if(this.working)throw new Error('请先完成或取消参考素材作业。');this.key='';this.dialog?.close();this.dialog?.remove();this.dialog=undefined;this.urls.splice(0).forEach(u=>URL.revokeObjectURL(u));this.record=undefined;this.ready=false}
 suspend():void{this.key='';this.dialog?.close();this.dialog?.remove();this.dialog=undefined;this.urls.splice(0).forEach(u=>URL.revokeObjectURL(u));this.record=undefined;this.ready=false}
 async open(asset:StudioAsset):Promise<void>{
  const s=this.options.state();if(!s||s.disabled||!['image','video'].includes(asset.kind))throw new Error('请先选择可用的图片或视频。');this.close();this.key=[s.projectId,s.sessionId,s.draft.id,asset.artifactId].join('/');const key=this.key
  const dialog=document.createElement('dialog');dialog.id='studio-reference-dialog';dialog.className='material-preview-dialog';dialog.setAttribute('aria-label','参考素材分析');this.dialog=dialog
  const heading=document.createElement('h3');heading.textContent='参考分析 · '+asset.artifactId;const note=document.createElement('p');note.className='muted';note.textContent='先生成真实参考帧，再交给当前 Assistant 分析。视频默认抽样三点，不能据此认定整段内容；建议需人工核对。'
  const status=document.createElement('p');status.id='reference-status';status.setAttribute('role','status');const gallery=document.createElement('div');gallery.id='reference-frames';gallery.className='reference-frames';const analysis=document.createElement('div');analysis.id='reference-analysis'
  const custom=document.createElement('details'),summary=document.createElement('summary'),times=document.createElement('input');summary.textContent='自选视频采样时间';times.id='reference-times';times.placeholder='例如 0, 1.5, 3（最多八点）';times.setAttribute('aria-label','参考视频采样时间');custom.append(summary,times);custom.hidden=asset.kind!=='video'
  const manager=document.createElement('details'),managerTitle=document.createElement('summary'),managerNote=document.createElement('p'),managerRows=document.createElement('div');manager.id='reference-management';managerNote.className='muted';managerNote.textContent='移除仅取消此视频的参考记录；原素材、参考 PNG 与已加入的制作背景保留。内容撤销不会恢复参考记录，可重新取帧。';managerRows.id='reference-management-rows';manager.append(managerTitle,managerNote,managerRows)
  const actions=document.createElement('div');actions.className='row';const add=(id:string,label:string,fn:()=>Promise<void>)=>{const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=()=>void fn().catch(e=>{const text=referenceError(e);if(key===this.key){status.textContent=text;this.options.notify(text)}else{const current=this.options.state();if(current&&[current.projectId,current.sessionId,current.draft.id,asset.artifactId].join('/')===key)this.options.notify(text)}});actions.append(b);return b}
  const prepare=add('reference-prepare','生成参考帧',async()=>{const value=times.value.trim(),timestamps=value?value.split(',').map(t=>Number(t.trim())):undefined;if(timestamps?.some(t=>!Number.isFinite(t)||t<0)||value&&value.split(',').some(t=>!t.trim())||timestamps&&(!timestamps.length||timestamps.length>8))throw new Error('请输入一至八个有限的非负秒数。');await run({operation:'prepare-reference',artifactId:asset.artifactId,assetKind:asset.kind,...(timestamps?{timestampsSeconds:timestamps}:{})})})
  const ask=add('reference-assistant','让 Assistant 分析参考 ↗',async()=>{if(!this.ready||!this.record)throw new Error('请先读取有效的参考帧。');await run({operation:'read-reference',referenceId:this.record.id});if(key===this.key&&this.record){const id=this.record.id;this.close();await this.options.ask(id)}})
  const apply=add('reference-apply','加入制作背景',async()=>{const current=this.options.state();if(!current||!this.ready||!this.record?.analysis)throw new Error('请先完成有效参考分析。');await run({operation:'apply-reference-notes',referenceId:this.record.id,beforeNotes:current.draft.preparation.notes});if(key===this.key)status.textContent='参考分析已加入制作背景；脚本和画面仍由你决定如何修改。'})
  const cancel=add('reference-cancel','取消作业',async()=>{this.stopRequested=true;cancel.disabled=true;status.textContent='正在停止并等待清理…';await this.options.cancel()}),close=add('reference-close','关闭',async()=>this.close());cancel.hidden=true
  const updateManager=(disabled:boolean)=>{
   const records=this.options.state()?.draft.referenceRecords??[];managerTitle.textContent='管理参考记录 · '+records.length+'/8';managerRows.replaceChildren()
   for(const record of records){const row=document.createElement('div'),label=document.createElement('span');row.className='row';row.dataset.referenceRecord=record.id;label.textContent=record.sourceArtifactId+' · '+record.createdAt.slice(0,16).replace('T',' ')+' · '+record.frames.length+' 帧 · '+(record.analysis?'已有分析':'待分析');row.append(label)
    if(record.sourceArtifactId===asset.artifactId){const view=document.createElement('button');view.textContent=record.id===this.record?.id?(this.ready?'当前记录':'重新读取'):'查看';view.disabled=disabled||(record.id===this.record?.id&&this.ready);view.dataset.referenceView=record.id;view.onclick=()=>void run({operation:'read-reference',referenceId:record.id}).catch(e=>{if(key===this.key){status.textContent=referenceError(e);this.options.notify(referenceError(e))}});row.append(view)}
    const remove=document.createElement('button');remove.textContent='移除记录';remove.disabled=disabled;remove.dataset.referenceRemove=record.id;remove.setAttribute('aria-label','移除 '+record.sourceArtifactId+' 的参考记录，素材保留');remove.onclick=()=>void run({operation:'remove-reference',referenceId:record.id}).then(()=>{if(key===this.key)status.textContent='已移除参考记录；素材、参考 PNG 和制作背景保留，可继续生成参考帧。'}).catch(e=>{if(key===this.key){status.textContent=referenceError(e);this.options.notify(referenceError(e))}});row.append(remove);managerRows.append(row)
   }
  }
  const update=()=>{const current=this.options.state(),disabled=this.working||!current||current.disabled||[current?.projectId,current?.sessionId,current?.draft.id,asset.artifactId].join('/')!==key;prepare.disabled=Boolean(disabled)||Boolean(current?.draft.referenceRecords&&current.draft.referenceRecords.length>=8);ask.disabled=Boolean(disabled)||!this.ready;apply.disabled=Boolean(disabled)||!this.ready||!this.record?.analysis||Boolean(this.record?.analysis&&current?.draft.preparation.notes.includes(referenceNotes(this.record)));times.disabled=Boolean(disabled);close.disabled=this.working;cancel.hidden=!this.working;cancel.disabled=!this.working;updateManager(Boolean(disabled))}
  const display=async()=>{
   if(key!==this.key)return;this.urls.splice(0).forEach(u=>URL.revokeObjectURL(u));gallery.replaceChildren();analysis.replaceChildren();if(!this.record){status.textContent='尚未生成参考帧。';update();return}
   const record=this.record;status.textContent=record.width+' × '+record.height+' · '+(record.kind==='video'?record.durationSeconds.toFixed(2)+' 秒（媒体） · 画面 '+record.videoRange!.startSeconds.toFixed(2)+'–'+record.videoRange!.endSeconds.toFixed(2)+' 秒 · '+record.frames.length+' 个采样帧':'静态图片')+' · 原文件指纹已核对'
   for(const [index,f]of record.frames.entries()){
    const block=document.createElement('article'),image=document.createElement('img'),label=document.createElement('button');block.dataset.referenceFrame=String(index);image.alt='参考帧 '+(index+1);label.textContent=(index+1)+' · 实际 '+f.seconds.toFixed(2)+' 秒';label.onclick=()=>void(async()=>{if(this.working)return;this.close();await this.options.preview(asset,f.seconds)})().catch(e=>this.options.notify(String(e)));block.append(image,label);gallery.append(block)
    const bytes=await this.options.bytes(f.artifactId);if(key!==this.key)return;const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)]));this.urls.push(url);image.src=url
   }
   if(record.analysis){const intro=document.createElement('p');intro.textContent=(record.analysisOrigin==='user'?'用户校正':'Assistant 分析')+' · 抽样建议，仍需核对';const text=document.createElement('p');text.textContent=record.analysis.summary;analysis.append(intro,text);for(const o of record.analysis.observations){const row=document.createElement('p');row.textContent='['+record.frames[o.frameIndex].seconds.toFixed(2)+' 秒] '+o.description+'\n可借鉴：'+o.adaptation;analysis.append(row)}const preview=document.createElement('details'),title=document.createElement('summary'),body=document.createElement('pre');title.textContent='将加入制作背景的内容';body.textContent=referenceNotes(record);preview.append(title,body);analysis.append(preview)}else{const text=document.createElement('p');text.textContent='尚无内容分析；让 Assistant 查看这些实际参考帧后提出建议。';analysis.append(text)}
   update()
  }
  const run=async(fields:Record<string,unknown>)=>{if(this.working||key!==this.key)throw new Error('请等待当前参考作业。');const current=this.options.state();if(!current||current.disabled||[current.projectId,current.sessionId,current.draft.id,asset.artifactId].join('/')!==key)throw new Error('参考所属视频已变化。');const owner={projectId:current.projectId,sessionId:current.sessionId,draftId:current.draft.id};this.working=true;this.stopRequested=false;update();status.textContent='正在处理参考素材…';try{const result=await this.options.command({...fields,draftId:owner.draftId,expectedRevision:current.draft.revision},owner);if(key!==this.key)return;if(result.removedReferenceId===this.record?.id){this.record=undefined;this.ready=false}if(result.reference){this.record=assertReferenceRecords([result.reference])[0];this.ready=true}await display()}catch(e){this.ready=false;if(key===this.key)status.textContent=this.stopRequested?'参考作业已停止，已保存的分析与素材保留。':referenceError(e);if(!this.stopRequested)throw new Error(referenceError(e),{cause:e})}finally{this.working=false;if(key===this.key)update()}}
  dialog.append(heading,note,status,custom,gallery,analysis,manager,actions);document.body.append(dialog);dialog.addEventListener('cancel',event=>{event.preventDefault();if(!this.working)this.close()});dialog.showModal()
  const existing=[...(s.draft.referenceRecords??[])].reverse().find(r=>r.sourceArtifactId===asset.artifactId);if(existing){this.record=existing;await run({operation:'read-reference',referenceId:existing.id})}else await display()
 }
}
