import {assertSourceCatalog,assertSourceCitation,assertSourceMediaAvailability,sourceText} from '../../../media-native/src/source-contract.js'
import type {SourceCatalog,SourceAcquisition,SourceCitation,SourceRequest,ProjectSource,SourceMediaAvailability} from '../../../media-native/src/source-contract.js'
interface SourceEditorContext {projectId:string;disabled:boolean;sourceIds:string[];scenes:{id:string;title:string}[];sceneId?:string}
/** Persistent form nodes retain selector/selection edits across Studio busy renders. */
export class StudioSourceEditor {
 private catalog?:SourceCatalog;private projectId='';private generation=0;private selected?:{source:ProjectSource;acquisition:SourceAcquisition;text:string;mediaAvailability:SourceMediaAvailability[]}
 constructor(private root:HTMLElement,private context:()=>SourceEditorContext|undefined,private command:(request:SourceRequest)=>Promise<unknown>,private selectSource:(id:string,selected:boolean)=>Promise<void>,private cite:(sceneId:string,citation:SourceCitation)=>Promise<void>,private preview:(artifactId:string)=>Promise<void>,private message:(text:string)=>void){
  root.innerHTML=`<fieldset><legend>来源与正文范围</legend><p class="muted">先选择正文范围，再确认素材候选。来源共用于此 Project；引用绑定原文，发表时间与事件时间分别记录。</p><button id="source-refresh">读取 Project 来源和页面</button><label>采集页面<select id="source-page"><option value="">当前页面</option></select></label><label>正文范围<input id="source-body" maxlength="500" placeholder="例如 article 或帖子正文元素"></label><details><summary>范围与元数据选项</summary><div class="source-form-grid"><label>正文匹配序号（从 0 开始）<input id="source-body-index" type="number" min="0" max="10000" value="0"></label><label>排除范围<textarea id="source-exclude" rows="2" placeholder="每行一个推荐、广告或头像元素"></textarea></label><label>素材范围（可独立选播放器）<input id="source-media" maxlength="500" placeholder="留空沿用正文范围"></label><label>素材匹配序号<input id="source-media-index" type="number" min="0" max="10000" value="0"></label><label>素材排除范围<textarea id="source-media-exclude" rows="2"></textarea></label><label>视频元素（播放器采集）<input id="source-video-selector" maxlength="500" placeholder="留空沿用素材范围"></label><label>视频匹配序号<input id="source-video-index" type="number" min="0" max="10000" value="0"></label><label>采集上限（秒）<input id="source-video-limit" type="number" min="1" max="1800" value="900"></label><label>作者元素<input id="source-author" maxlength="500" placeholder="留空保持未知"></label><label>发表时间元素<input id="source-published" maxlength="500" placeholder="保留页面显示的原始时间"></label><label>观看限制提示元素<input id="source-access" maxlength="500" placeholder="例如显示试看提示的播放器区域"></label></div></details><button id="source-collect">采集限定正文与素材候选</button><label>已有来源 / 采集记录<select id="source-record"><option value="">先读取来源</option></select></label><div id="source-detail"></div><label>原文（选中文字可添加引用）<textarea id="source-original" rows="8" readonly></textarea></label><div id="source-candidates"></div><label>事件发生时间<input id="source-event" maxlength="80" placeholder="未知；不会使用采集时间代替"></label><button id="source-confirm">确认候选与事件时间</button><button id="source-use">加入此次视频来源</button><details><summary>引用选中的原文</summary><label>目标分镜<select id="source-scene"></select></label><label>依据类型<select id="source-kind"><option value="fact">事实引用（待核查）</option><option value="opinion">作者观点</option></select></label><label>要支持的陈述<textarea id="source-claim" rows="2" maxlength="2000"></textarea></label><label>来源冲突<select id="source-conflict"><option value="pending">待确认</option><option value="conflicting">存在冲突</option></select></label><button id="source-cite">把选中文字引用到分镜</button><p class="muted">事实引用表示证据用途；合成不会宣称事实核查通过。</p></details></fieldset>`
  this.node<HTMLButtonElement>('source-refresh').onclick=this.guard(()=>this.load())
  this.node<HTMLButtonElement>('source-collect').onclick=this.guard(()=>this.collect())
  this.node<HTMLSelectElement>('source-record').onchange=this.guard(()=>this.readSelected())
  this.node<HTMLButtonElement>('source-confirm').onclick=this.guard(()=>this.confirm())
  this.node<HTMLButtonElement>('source-use').onclick=this.guard(async()=>{const selected=this.required(),context=this.context()!;await this.selectSource(selected.source.id,!context.sourceIds.includes(selected.source.id));this.render()})
  this.node<HTMLButtonElement>('source-cite').onclick=this.guard(async()=>{const selected=this.required(),text=this.node<HTMLTextAreaElement>('source-original'),startCharacter=text.selectionStart,endCharacter=text.selectionEnd;if(startCharacter===endCharacter)throw new Error('请先在原文中选择引用文字。');const citation=assertSourceCitation({sourceId:selected.source.id,acquisitionId:selected.acquisition.id,startCharacter,endCharacter,quote:selected.text.slice(startCharacter,endCharacter),kind:this.value('source-kind'),claim:this.value('source-claim'),conflict:this.value('source-conflict'),eventAt:selected.acquisition.eventAt});await this.cite(this.value('source-scene'),citation);this.message('引用已关联原文范围，核查状态保留待确认。')})
 }
 private node<T extends HTMLElement>(id:string):T{return this.root.querySelector<T>('#'+id)!}
 private value(id:string):string{return this.node<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(id).value}
 private guard(fn:()=>Promise<void>):()=>void{return ()=>{void fn().catch(error=>this.message(error instanceof Error?error.message:String(error)))}}
 private required(){if(!this.selected)throw new Error('请先读取一条来源原文。');return this.selected}
 render():void{
  const context=this.context();if(context?.projectId!==this.projectId){this.projectId=context?.projectId??'';this.generation++;this.catalog=undefined;this.selected=undefined;this.node('source-detail').replaceChildren();this.node<HTMLTextAreaElement>('source-original').value='';this.node('source-candidates').replaceChildren();this.node<HTMLSelectElement>('source-record').replaceChildren(new Option('先读取来源',''));this.node<HTMLSelectElement>('source-page').replaceChildren(new Option('当前页面',''))}
  this.root.querySelector<HTMLFieldSetElement>('fieldset')!.disabled=!context||context.disabled
  const scenes=this.node<HTMLSelectElement>('source-scene'),previous=scenes.value,next=(context?.scenes??[]).map(scene=>new Option(scene.title,scene.id))
  if(scenes.options.length!==next.length||next.some((item,index)=>scenes.options[index]?.value!==item.value||scenes.options[index]?.text!==item.text)){scenes.replaceChildren(...next);scenes.value=next.some(scene=>scene.value===previous)?previous:context?.sceneId??next[0]?.value??''}
  this.node<HTMLButtonElement>('source-cite').disabled=!context?.scenes.length||!this.selected?.text
  this.node<HTMLButtonElement>('source-use').disabled=!this.selected;this.node('source-use').textContent=this.selected&&context?.sourceIds.includes(this.selected.source.id)?'移出此次视频来源':'加入此次视频来源'
  this.node<HTMLButtonElement>('source-confirm').disabled=!this.selected;this.node<HTMLButtonElement>('source-collect').disabled=!this.catalog
 }
 private async load(){const project=this.projectId,generation=this.generation,result=await this.command({operation:'list'});if(project!==this.projectId||generation!==this.generation)return;const value=result as {catalog:unknown;pages:{id:string;url:string;title:string}[]};this.catalog=assertSourceCatalog(value.catalog);this.node<HTMLSelectElement>('source-page').replaceChildren(new Option('当前页面',''),...value.pages.map(page=>new Option(page.title+' · '+page.url,page.id)));this.records();this.render()}
 private records(){const list=this.node<HTMLSelectElement>('source-record'),previous=list.value;list.replaceChildren(new Option('选择来源 / 采集记录',''),...(this.catalog?.sources??[]).flatMap(source=>source.acquisitions.map(acquisition=>new Option((acquisition.title||source.url)+' · '+acquisition.capturedAt+' · '+acquisition.result,source.id+'.'+acquisition.id))));list.value=previous}
 private async collect(){if(!this.catalog)throw new Error('请先读取当前 Project 来源。');const exclusions=(id:string)=>this.value(id).split('\n').map(s=>s.trim()).filter(Boolean);const project=this.projectId,generation=this.generation
  const result=await this.command({operation:'collect',expectedRevision:this.catalog.revision,bodySelector:this.value('source-body'),index:Number(this.value('source-body-index')),excludeSelectors:exclusions('source-exclude'),...(this.value('source-page')?{tabId:this.value('source-page')}:{}),...(this.value('source-media')?{mediaSelector:this.value('source-media'),mediaIndex:Number(this.value('source-media-index'))}:{}),...(this.value('source-media-exclude').trim()?{mediaExcludeSelectors:exclusions('source-media-exclude')}:{}),...(this.value('source-author')?{authorSelector:this.value('source-author')}:{}),...(this.value('source-published')?{publishedSelector:this.value('source-published')}:{}),...(this.value('source-access')?{accessSelector:this.value('source-access')}:{})})
  if(project!==this.projectId||generation!==this.generation)return;const value=result as {catalog:unknown;sourceId:string;acquisitionId:string};this.catalog=assertSourceCatalog(value.catalog);this.records();this.node<HTMLSelectElement>('source-record').value=value.sourceId+'.'+value.acquisitionId;await this.readSelected();this.message('限定原文已保存；素材仍是待确认候选。')
 }
 private async readSelected(){const key=this.value('source-record'),[sourceId,acquisitionId]=key.split('.');this.selected=undefined;this.node('source-detail').replaceChildren();this.node('source-candidates').replaceChildren();this.node<HTMLTextAreaElement>('source-original').value='';this.render();if(!sourceId||!acquisitionId)return;const generation=++this.generation,project=this.projectId,value=await this.command({operation:'read',sourceId,acquisitionId}) as {text:unknown;mediaAvailability:unknown}
  if(generation!==this.generation||project!==this.projectId)return;const source=this.catalog?.sources.find(source=>source.id===sourceId),acquisition=source?.acquisitions.find(acquisition=>acquisition.id===acquisitionId);if(!source||!acquisition)throw new Error('来源已变化，请重新读取。');this.selected={source,acquisition,text:sourceText(value.text,'original',50000),mediaAvailability:assertSourceMediaAvailability(value.mediaAvailability)};this.detail();this.render()
 }
 private detail(){const {source,acquisition,text,mediaAvailability}=this.required();const details=this.node('source-detail');details.replaceChildren();for(const [label,value] of [['页面',source.url],['作者',acquisition.author??'未知'],['发表时间',acquisition.publishedAt??'未知'],['采集时间',acquisition.capturedAt],['事件时间',acquisition.eventAt??'未知'],['正文范围',acquisition.scope.selector],['获取状态',acquisition.result],['观看限制',acquisition.access],['状态说明',acquisition.error??'无']]){const paragraph=document.createElement('p');paragraph.textContent=label+'：'+value;details.append(paragraph)}this.node<HTMLTextAreaElement>('source-original').value=text;this.node<HTMLInputElement>('source-event').value=acquisition.eventAt??''
  const candidates=this.node('source-candidates');candidates.replaceChildren();for(const candidate of acquisition.candidates){const row=document.createElement('label');row.className='source-candidate';const check=document.createElement('input');check.type='checkbox';check.dataset.candidate=candidate.id;check.checked=acquisition.confirmedCandidateIds.includes(candidate.id);const label=document.createElement('span');label.textContent=candidate.role+' / '+candidate.kind+' · '+candidate.url;row.append(check,label);candidates.append(row);if(acquisition.confirmedCandidateIds.includes(candidate.id)){const acquire=document.createElement('button');acquire.type='button';acquire.textContent='获取并验证素材';acquire.onclick=this.guard(()=>this.acquire(candidate.id));row.append(acquire);if(candidate.kind==='video'||candidate.kind==='source'){const capture=document.createElement('button');capture.type='button';capture.textContent='采集此播放器';capture.onclick=this.guard(()=>this.acquire(candidate.id,'capture'));row.append(capture)}}for(const media of acquisition.media.filter(media=>media.candidateId===candidate.id)){const status=document.createElement('p');const availability=mediaAvailability.find(item=>item.mediaId===media.id);status.textContent=media.state+' · '+(media.artifactId??media.error??'')+(media.artifactId?' · 当前文件：'+(availability?.artifactStatus??'未核对')+' / 证明：'+(availability?.proofStatus??'未核对'):'');row.append(status);if(media.artifactId){const preview=document.createElement('button');preview.type='button';preview.textContent='预览已保存素材';preview.disabled=!availability?.available;preview.onclick=this.guard(()=>this.preview(media.artifactId!));row.append(preview)}}}if(!acquisition.candidates.length){const empty=document.createElement('p');empty.textContent='限定范围没有可用素材候选。';candidates.append(empty)}
 }
 private async acquire(candidateId:string,method:'download'|'capture'='download'){const {source,acquisition}=this.required();if(!this.catalog)return;const project=this.projectId,generation=this.generation,result=await this.command({operation:'acquire',expectedRevision:this.catalog.revision,sourceId:source.id,acquisitionId:acquisition.id,candidateId,method,...(method==='capture'?{videoSelector:this.value('source-video-selector').trim()||acquisition.mediaScope.selector,videoIndex:this.value('source-video-selector').trim()?Number(this.value('source-video-index')):acquisition.mediaScope.index,maxDurationMs:Math.round(Number(this.value('source-video-limit'))*1000)}:{}),...(this.value('source-page')?{tabId:this.value('source-page')}:{})}) as {catalog:unknown;state:string;error?:string};if(project!==this.projectId||generation!==this.generation)return;this.catalog=assertSourceCatalog(result.catalog);this.records();await this.readSelected();this.message('素材获取：'+result.state+(result.error?' · '+result.error:''))}
 private async confirm(){const {source,acquisition}=this.required();if(!this.catalog)return;const candidateIds=[...this.root.querySelectorAll<HTMLInputElement>('[data-candidate]')].filter(input=>input.checked).map(input=>input.dataset.candidate!);const project=this.projectId,generation=this.generation,result=await this.command({operation:'confirm',expectedRevision:this.catalog.revision,sourceId:source.id,acquisitionId:acquisition.id,candidateIds,eventAt:this.value('source-event').trim()||null}) as {catalog:unknown};if(project!==this.projectId||generation!==this.generation)return;this.catalog=assertSourceCatalog(result.catalog);this.records();await this.readSelected();this.message('候选确认已保存；确认不表示已经下载。')}
}
