import {sceneVisuals} from '../../../media-native/src/visual-segments.js'
import {mediaRecord} from '../../../media-native/src/media-contract.js'
import {assertSpeechEvidence} from '../../../media-native/src/speech-contract.js'
import type {CaptionCue} from '../../../media-native/src/composition-contract.js'
import type {VideoDraft,StudioScene,StudioRequest} from '../studio-contract.js'
interface Context {projectId:string;draft:VideoDraft;scene:StudioScene;disabled:boolean}
interface Scope {projectId:string;draftId:string;sceneId:string;revision:number}
export class StudioOriginalSpeechEditor{
 private key='';private dirty=false;private scope?:Scope;private rows:{start:HTMLInputElement;end:HTMLInputElement;text:HTMLTextAreaElement}[]=[];private url?:string;private generation=0
 constructor(private root:HTMLElement,private context:()=>Context|undefined,private command:(request:Partial<StudioRequest>,scope?:Scope)=>Promise<unknown>,private load:(id:string)=>Promise<Uint8Array>,private message:(text:string)=>void){}
 hasPending():boolean{return this.dirty}
 flush():void{if(this.dirty)throw new Error('原声字幕尚有未保存校正，请先应用或重新读取识别结果。')}
 clear():void{this.generation++;if(this.url)URL.revokeObjectURL(this.url);this.url=undefined;for(const video of this.root.querySelectorAll('video')){video.pause();video.removeAttribute('src');video.load()}this.key='';this.dirty=false;this.scope=undefined;this.rows=[];this.root.replaceChildren()}
 private run(fn:()=>Promise<void>):void{void Promise.resolve().then(fn).catch(e=>this.message(e instanceof Error?e.message:String(e)))}
 render():void{const context=this.context();if(!context){this.clear();return}const key=context.projectId+':'+context.draft.id+':'+context.scene.id;if(key===this.key){for(const node of this.root.querySelectorAll('button,input,textarea,select'))(node as HTMLButtonElement).disabled=context.disabled||(node as HTMLElement).dataset.blocked==='true';return}if(this.dirty)return;this.clear();this.key=key
  const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='视频原声 · 识别、试听与校正';details.append(summary);this.root.append(details)
  const visuals=sceneVisuals(context.scene),segment=document.createElement('select');segment.id='source-speech-segment';visuals.forEach((v,i)=>{if(v.videoArtifactId)segment.append(new Option(`${i+1} · ${v.videoArtifactId}`,String(i)))});const model=document.createElement('select');model.id='source-speech-model';model.append(new Option('Whisper base','base'),new Option('Whisper small','small'));const language=document.createElement('select');language.id='source-speech-language';language.append(new Option('自动识别语言','auto'),new Option('英语','en'),new Option('中文','zh'));details.append(segment,model,language)
  const controls=document.createElement('div'),evidence=document.createElement('div'),player=document.createElement('div');details.append(controls,player,evidence);let evidenceSourceId:string|undefined;segment.onchange=()=>{evidenceSourceId=undefined}
  const button=(label:string,id:string,fn:()=>Promise<void>)=>{const b=document.createElement('button');b.textContent=label;b.id=id;b.disabled=context.disabled;b.onclick=()=>this.run(fn);controls.append(b);return b}
  const show=(raw:unknown)=>{const result=mediaRecord(raw),proof=assertSpeechEvidence(result.evidence),current=this.context()!;const candidate=mediaRecord(result.candidate);segment.value=String(candidate.segmentIndex);evidenceSourceId=proof.sourceArtifactId;this.scope={projectId:current.projectId,draftId:current.draft.id,sceneId:current.scene.id,revision:current.draft.revision};this.rows=[];evidence.replaceChildren();const note=document.createElement('p');note.textContent=result.stale?'原视频已变化；这些结果只供回溯，请重新识别。':'识别时间为原视频秒数；先试听校正，再应用到分镜。模型输出不代表精确声学标注。';evidence.append(note)
   for(const cue of proof.segments){const row=document.createElement('div');row.className='caption-row';const start=document.createElement('input'),end=document.createElement('input'),text=document.createElement('textarea');start.type=end.type='number';start.step=end.step='.01';start.value=String(cue.startSeconds);end.value=String(cue.endSeconds);text.value=cue.text;text.maxLength=200;start.setAttribute('aria-label','原视频开始秒');end.setAttribute('aria-label','原视频结束秒');text.setAttribute('aria-label','原声识别原文');for(const node of [start,end,text])node.oninput=()=>{this.dirty=true};row.append(start,end,text);const remove=document.createElement('button');remove.textContent='移除此识别段';remove.onclick=()=>{this.dirty=true;this.rows=this.rows.filter(item=>item.start!==start);row.remove()};row.append(remove);const warning=document.createElement('span');warning.textContent=cue.warnings.join(' · ');row.append(warning);evidence.append(row);this.rows.push({start,end,text})}
   const heard=document.createElement('input');heard.type='checkbox';heard.id='source-speech-heard';const label=document.createElement('label');label.append(heard,'我已核听并校正这些字幕');evidence.append(label);const apply=document.createElement('button');apply.textContent='应用为当前分镜原声字幕';apply.id='source-speech-apply';apply.dataset.blocked=String(result.stale===true);apply.disabled=current.disabled||result.stale===true;apply.onclick=()=>this.run(async()=>{if(!heard.checked)throw new Error('请先试听并确认校正。');const sourceCues:CaptionCue[]=this.rows.map(row=>({startSeconds:Number(row.start.value),endSeconds:Number(row.end.value),text:row.text.value}));await this.command({operation:'apply-source-captions',sourceCues},this.scope);this.dirty=false;this.scope=undefined;this.message('原声字幕已保存；可分别编辑原文与译文。')});evidence.append(apply)
  }
  button('识别所选视频原声','source-speech-recognize',async()=>{this.flush();if(!segment.value)throw new Error('请先绑定视频画面。');show(await this.command({operation:'recognize-source',segmentIndex:Number(segment.value),speechModel:model.value as 'base'|'small',speechLanguage:language.value as 'zh'|'en'|'auto'}));details.open=true})
  button('读取已有原声识别','source-speech-read',async()=>{this.dirty=false;show(await this.command({operation:'read-source-speech'}));details.open=true})
  button('试听原视频','source-speech-listen',async()=>{const v=sceneVisuals(this.context()!.scene)[Number(segment.value)];const artifactId=evidenceSourceId??v?.videoArtifactId;if(!artifactId)throw new Error('请选择视频。');const generation=this.generation,data=await this.load(artifactId);if(generation!==this.generation)return;if(this.url)URL.revokeObjectURL(this.url);this.url=URL.createObjectURL(new Blob([data as Uint8Array<ArrayBuffer>]));const video=document.createElement('video');video.controls=true;video.dataset.artifactId=artifactId;video.src=this.url;video.style.maxWidth='100%';video.onloadedmetadata=()=>{video.currentTime=v?.videoArtifactId===artifactId?v.sourceStartSeconds:0};player.replaceChildren(video);details.open=true})
  button('解除原声时间关联（保留字幕）','source-speech-detach',async()=>{this.flush();await this.command({operation:'detach-source-captions'});this.message('字幕已独立保留，剪裁与变速不再自动校验它的时间。')})
  const limit=document.createElement('p');limit.className='muted';limit.textContent='固定本地模型；单个原视频音轨最多180秒。识别保留已有字幕，应用校正才替换当前分镜字幕。剪裁或变速后重新应用，字幕共享新时间。';details.append(limit)
 }
}
