import type {CardSpec,CardMotion} from '../../../media-native/src/card-templates.js'
import {cardTemplate} from '../../../media-native/src/card-templates.js'
import type {DetailedCardSpec,CardHighlight,CardReading} from '../../../media-native/src/card-details.js'
interface DetailsOptions {images:{artifactId:string;name:string}[];change(spec:CardSpec):void;pick(kind:'reading'|'highlight',line?:number):void;save():void}
/** Only the selected variant's bounded slots. No JSON editor and no independent hidden layers. */
export function cardDetailsForm(spec:DetailedCardSpec,options:DetailsOptions):HTMLElement {
 const root=document.createElement('section');root.className='card-details-form';root.setAttribute('aria-label','卡片专用内容')
 const next=structuredClone(spec)
 const field=(labelText:string,value:string,max:number,write:(value:string)=>void,parent:HTMLElement=root)=>{const label=document.createElement('label');label.textContent=labelText;const input=document.createElement('textarea');input.rows=max>64?3:1;input.maxLength=max;input.value=value;input.setAttribute('aria-label',labelText);input.oninput=()=>{write(input.value);options.change(next)};label.append(input);parent.append(label);return input}
 const select=(labelText:string,value:string,choices:readonly (readonly [string,string])[],write:(value:string)=>void,parent:HTMLElement=root)=>{const label=document.createElement('label');label.textContent=labelText;const input=document.createElement('select');input.setAttribute('aria-label',labelText);for(const [id,name]of choices){const option=document.createElement('option');option.value=id;option.textContent=name;input.append(option)}input.value=value;input.onchange=()=>{write(input.value);options.change(next)};label.append(input);parent.append(label)}
 const numeric=(labelText:string,value:number,write:(value:number)=>void,parent:HTMLElement=root)=>{const label=document.createElement('label');label.textContent=labelText;const input=document.createElement('input');input.type='number';input.value=String(value);input.step='any';input.setAttribute('aria-label',labelText);input.oninput=()=>{write(input.value.trim()?Number(input.value):NaN);options.change(next)};label.append(input);parent.append(label)}
 const image=(label:string,value:string,write:(value:string)=>void)=>select(label,value,[['','请选择项目图片'],...options.images.map(a=>[a.artifactId,a.name] as const)],write)
 const button=(name:string,fn:()=>void,parent:HTMLElement=root)=>{const b=document.createElement('button');b.textContent=name;b.onclick=fn;parent.append(b);return b}
 if('quote'in next){field('原句（可核对节选）',next.quote.excerpt,160,v=>{next.quote.excerpt=v});field('译文（可选，明确标注）',next.quote.translation,160,v=>{next.quote.translation=v});field('引述来源 / 作者',next.quote.attribution,240,v=>{next.quote.attribution=v});select('原文与译文',next.quote.display,[['simultaneous','同时显示'],['staged','先原文后译文']],v=>{next.quote.display=v as 'simultaneous'|'staged'})}
 if('person'in next){image('人物图',next.person.artifactId??'',v=>{if(v.trim())next.person.artifactId=v;else delete next.person.artifactId});field('姓名',next.person.name,32,v=>{next.person.name=v});field('身份（可选）',next.person.role,64,v=>{next.person.role=v});select('人物位置',next.person.layout,[['right','右侧人物'],['corner','人物角标']],v=>{next.person.layout=v as 'right'|'corner'})}
 if(next.templateId==='metric/backdrop'){numeric('数值',next.value,v=>{next.value=v});numeric('小数位',next.decimals,v=>{next.decimals=v as 0|1|2});field('单位',next.unit,8,v=>{next.unit=v});select('数字阶段',next.phase,[['hold','保留大字'],['to-evidence','退回背景依据']],v=>{next.phase=v as 'hold'|'to-evidence'});numeric('大字停留（秒）',next.holdSeconds,v=>{next.holdSeconds=v})}
 if(next.templateId==='diagram/to-target'){
  next.objects.forEach((n,i)=>{field('对象 '+(i+1),n.label,32,v=>{n.label=v});image('对象 '+(i+1)+' 图片（可选）',n.imageArtifactId??'',v=>{if(v.trim())n.imageArtifactId=v;else delete n.imageArtifactId})});field('共同目标',next.target.label,32,v=>{next.target.label=v});image('目标图片（可选）',next.target.imageArtifactId??'',v=>{if(v.trim())next.target.imageArtifactId=v;else delete next.target.imageArtifactId});field('关系',next.relation,24,v=>{next.relation=v});button(next.objects.length===2?'＋ 第三个对象':'删除第三个对象',()=>{if(next.objects.length===2)next.objects.push({label:''});else next.objects.pop();options.change(next);options.save()})
 }
 if(next.templateId==='diagram/range'){
  select('范围模式',next.range.mode,[['symbolic','符号示意 · 非比例'],['numeric','真实数值 · 按比例']],v=>{next.range=v==='numeric'?{mode:'numeric',axisLabel:next.range.axisLabel,minimum:0,maximum:1,start:0,end:.5,thresholds:[],unit:'',condition:next.range.condition}:{mode:'symbolic',axisLabel:next.range.axisLabel,regionLabel:'',thresholdLabels:[],condition:next.range.condition};options.change(next);options.save()})
  const r=next.range;field('轴含义',r.axisLabel,48,v=>{r.axisLabel=v});field('条件 / 限定',r.condition,100,v=>{r.condition=v})
  if(r.mode==='numeric'){for(const [key,label]of [['minimum','轴起点'],['maximum','轴终点'],['start','区域起点'],['end','区域终点']] as const)numeric(label,r[key],v=>{r[key]=v});field('单位',r.unit,8,v=>{r.unit=v});field('阈值（至多两个，逗号分隔）',r.thresholds.join(','),64,v=>{r.thresholds=v.trim()?v.split(/[,，]/).map(t=>t.trim()?Number(t):NaN):[]})}else{field('已达区域',r.regionLabel,48,v=>{r.regionLabel=v});field('阈值标签（至多两个，逗号分隔）',r.thresholdLabels.join(','),65,v=>{r.thresholdLabels=v.trim()?v.split(/[,，]/).map(t=>t.trim()):[]})}
 }
 const motions=cardTemplate(next.templateId).motions.filter(m=>next.templateId!=='diagram/image'||m==='none')
 if(motions.length>1)select('表现',next.motion??'none',motions.map(m=>[m,({none:'静态','fade-in':'淡入',wipe:'整句擦入','count-up':'数字递增','reveal-items':'逐项出现'} as Partial<Record<CardMotion,string>>)[m]??m]),v=>{next.motion=v as DetailedCardSpec['motion']})
 if(['evidence/reading','evidence/highlight','evidence/translation','evidence/person-quote','diagram/image'].includes(next.templateId)){
  const evidence=next as DetailedCardSpec&{reading?:CardReading;highlights?:CardHighlight[]},details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='阅读与重点 · 源图坐标';details.append(summary);root.append(details)
  const max='quote'in next?1:3
  if(evidence.reading){const r=evidence.reading;select('阅读方式',r.mode,[['whole-to-detail','整页到重点'],['detail-to-whole','局部到全貌'],['sequence','依次阅读']],v=>{r.mode=v as CardReading['mode']},details);select('结束画面',String(r.returnToWhole),[['false','停在重点'],['true','回到全貌']],v=>{r.returnToWhole=v==='true'},details)
   r.targets.forEach((t,i)=>{field('阅读目标 '+(i+1),t.name,32,v=>{t.name=v},details);const p=document.createElement('small');p.textContent=t.source.artifactId+' · '+t.source.sha256.slice(0,8);details.append(p);button('删除阅读目标 '+(i+1),()=>{r.targets.splice(i,1);if(!r.targets.length)delete evidence.reading;options.change(next);options.save()},details);if(i>0)button('上移目标 '+(i+1),()=>{[r.targets[i-1],r.targets[i]]=[r.targets[i],r.targets[i-1]];options.change(next);options.save()},details)})
   button('取消阅读配方',()=>{delete evidence.reading;options.change(next);options.save()},details)
  }
  if((evidence.reading?.targets.length??0)<max)button('＋ 在预览框选阅读目标',()=>options.pick('reading'),details)
  evidence.highlights?.forEach((h,i)=>{field('重点 '+(i+1),h.name,32,v=>{h.name=v},details);select('重点 '+(i+1)+' 样式',h.style,[['outline','框线'],['fill','底色'],['invert','原像素反白']],v=>{h.style=v as CardHighlight['style']},details);numeric('重点 '+(i+1)+' 开始秒',h.startSeconds,v=>{h.startSeconds=v},details);numeric('重点 '+(i+1)+' 结束秒',h.endSeconds,v=>{h.endSeconds=v},details);const p=document.createElement('small');p.textContent=h.source.artifactId+' · '+h.source.sha256.slice(0,8)+' · '+h.rects.length+' 行';details.append(p);if(h.rects.length<3)button('＋ 框选此重点下一行',()=>options.pick('highlight',i),details);button('删除重点 '+(i+1),()=>{evidence.highlights!.splice(i,1);options.change(next);options.save()},details);if(i>0)button('上移重点 '+(i+1),()=>{const previous=evidence.highlights![i-1],current=evidence.highlights![i];[previous.startSeconds,current.startSeconds]=[current.startSeconds,previous.startSeconds];[previous.endSeconds,current.endSeconds]=[current.endSeconds,previous.endSeconds];[evidence.highlights![i-1],evidence.highlights![i]]=[current,previous];options.change(next);options.save()},details)})
  if((evidence.highlights?.length??0)<max)button('＋ 在预览框选原句重点',()=>options.pick('highlight'),details)
  const note=document.createElement('small');note.textContent='时序由模板估算，可按秒校正；未声称语音逐词对齐。换源需删除旧目标后重新框选。';details.append(note)
 }
 button('保存专用内容',options.save)
 return root
}
