import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {app,BrowserWindow,ipcMain,session,webContents} from 'electron'
import type {WebContents} from 'electron'
import {captureRendererEvidence} from './renderer-evidence.js'
import {VideoStudioRuntime} from '../packages/feature-video/src/studio-runtime.js'
import {newStudioScene,draftReadiness} from '../packages/feature-video/src/studio-contract.js'
import type {VideoDraft} from '../packages/feature-video/src/studio-contract.js'
import {VideoStudioStore} from '../packages/feature-video/src/studio-store.js'
import {studioService} from '../packages/feature-video/src/studio-service.js'
import type {StudioKernel} from '../packages/feature-video/src/studio-service.js'
import {MediaController} from '../packages/media-native/src/media-controller.js'
import {BrowserKernel} from '../packages/browser-capability/src/browser-kernel.js'
import {BrowserCapabilityRegistry} from '../packages/browser-capability/src/browser-capability-registry.js'
import {GlobalSettingsStore} from '../packages/platform/src/global-settings-store.js'
import {mediaRecord} from '../packages/media-native/src/media-contract.js'
import {assertSpeechEvidence} from '../packages/media-native/src/speech-contract.js'
import product from '../apps/bmw/product.js'
const temporary=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'bmw-studio-next-'))),project={id:'next-project',name:'Video Studio acceptance',directory:path.join(temporary,'project')},artifacts=path.join(project.directory,'artifacts'),proof=process.env.BMW_VALIDATION_DIR??'.bmw-runtime/studio-next'
fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(path.join(temporary,'profile'));fs.mkdirSync(proof,{recursive:true});app.setPath('userData',path.join(temporary,'profile'))
let host:BrowserWindow,studio:WebContents,runtime:VideoStudioRuntime,media:MediaController,phase='initializing',exitCode=0
const timeout=setTimeout(()=>{console.error('Studio next timed out: '+phase);app.exit(1)},240000)
async function js<T>(code:string):Promise<T>{return studio.executeJavaScript(code,true)}
async function wait(condition:()=>Promise<unknown>,label:string):Promise<void>{phase=label;const end=Date.now()+25000;while(Date.now()<end){if(await condition())return;await new Promise(resolve=>setTimeout(resolve,80))}throw new Error('Timed out: '+label+' · '+(studio&&!studio.isDestroyed()?await js("document.getElementById('status').textContent"):'no renderer'))}
async function click(id:string):Promise<void>{await js(`document.getElementById(${JSON.stringify(id)}).click()`)}
async function run():Promise<void>{try{
 await app.whenReady();const isolated=session.fromPartition('studio-next-'+process.pid);host=new BrowserWindow({show:false,width:1380,height:980,webPreferences:{session:isolated,sandbox:true,contextIsolation:true,nodeIntegration:false}});await host.loadURL('data:text/html,<title>Studio fixture</title>')
 const registry=new BrowserCapabilityRegistry(product);media=new MediaController({session:isolated,preloadPath:path.resolve('packages/media-native/src/preload/media-preload.cjs'),pagePath:path.resolve('packages/media-native/src/media/media.html'),artifactsDirectory:artifacts,resolveArtifactsDirectory:()=>artifacts,onStatus:()=>{}})
 const kernel=new BrowserKernel({window:host,session:isolated,capabilityRegistry:registry,permissionStore:{hasAgentControl:()=>true},projectStore:{active:()=>project},artifactsDirectory:artifacts,sessionContinuity:undefined,settingsStore:new GlobalSettingsStore({filePath:path.join(temporary,'settings.json'),onState:undefined}),allowedActions:registry.allowedActions,onState:undefined});kernel.setRecordingController(media)
 const owner={projectId:project.id,sessionId:'next-session'},execute=(request:unknown)=>studioService(kernel as unknown as StudioKernel).execute(request,undefined,owner),store=new VideoStudioStore(project.directory,owner.sessionId),prompts:string[]=[]
 runtime=new VideoStudioRuntime();runtime.configure({browserKernel:kernel as unknown as StudioKernel,projectStore:{active:()=>project},getMainWindow:()=>host,getShellWebContents:()=>host.webContents,getTheme:()=> 'light',setWorkspaceMode:()=>{},getCurrentSessionId:()=>owner.sessionId,isProjectChanging:()=>false,revealAgent:()=>{},enqueueAssistant:async(sessionId:string,prompt:string)=>{assert.equal(sessionId,owner.sessionId);prompts.push(prompt);return 'test-translation-turn'},synchronizeAgentProject:async()=>({sessionId:owner.sessionId})});runtime.installIpc(ipcMain)
 const png=await host.webContents.executeJavaScript("(()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const x=c.getContext('2d');x.fillStyle='#d83333';x.fillRect(0,0,320,180);x.fillStyle='#ffeebb';x.fillRect(40,30,100,80);return c.toDataURL('image/png').split(',')[1]})()") as string;fs.writeFileSync(path.join(artifacts,'source.png'),Buffer.from(png,'base64'))
 phase='Real source track';let sourceArtifactId:string
 if(process.env.BMW_STUDIO_SOURCE){sourceArtifactId='speech-source'+path.extname(process.env.BMW_STUDIO_SOURCE);fs.copyFileSync(process.env.BMW_STUDIO_SOURCE,path.join(artifacts,sourceArtifactId))}
 else{const narration=mediaRecord(await media.narrate({text:'Open the project. Select the video. Review the result.',provider:'local-matcha',voice:'local-zh-en',ratePercent:0}));const original=mediaRecord(await media.compose({title:'Synthetic source fixture',width:640,height:360,fps:12,music:false,watermark:{enabled:false},scenes:[{title:'Original source',durationSeconds:Number(narration.durationSeconds)+1,imageArtifactId:'source.png',audioArtifactId:narration.artifactId,captions:[]}]}));sourceArtifactId=String(original.artifactId)}
 const otherSourceId='other-source'+path.extname(sourceArtifactId);fs.copyFileSync(path.join(artifacts,sourceArtifactId),path.join(artifacts,otherSourceId));
 let draft=store.create('原声双语与表达模板');draft.width=640;draft.height=360;draft.fps=12;draft.music=false;draft.watermark={...draft.watermark!,enabled:false};draft.scenes=[{...newStudioScene('original','原声 · 试听与双语'),durationSeconds:4,visualSegments:[{videoArtifactId:otherSourceId,durationSeconds:1,sourceStartSeconds:0,playbackRate:1,zoom:1,transition:'cut',transitionSeconds:.05},{videoArtifactId:sourceArtifactId,durationSeconds:3,sourceStartSeconds:0,playbackRate:1,zoom:1,keepSourceAudio:true,transition:'cut',transitionSeconds:.05}],captions:[{startSeconds:0,endSeconds:1,text:'Independent retained'}]}, {...newStudioScene('summary','三点总结'),durationSeconds:2,sceneTemplate:{kind:'summary',emphasisIndex:1},bullets:['先取得真实材料','让信息关系清楚可见','核对后再交付'],showSceneNumber:false,captions:[]},{...newStudioScene('comparison','表达方案对比'),durationSeconds:2,sceneTemplate:{kind:'comparison'},bullets:['原方案：逐项堆叠信息','改进方案：比较关系明确'],showSceneNumber:false,captions:[]},{...newStudioScene('screenshot','截图解读'),durationSeconds:2,sceneTemplate:{kind:'screenshot'},imageArtifactId:'source.png',bullets:['这一处标记解释了操作结果'],showSceneNumber:false,captions:[]}];draft=store.update(draft.id,draft.revision,draft)
 assert.ok(draftReadiness(draft).issues.some(issue=>issue.code==='duration-unmeasured'));const checked=mediaRecord(await execute({operation:'check',draftId:draft.id,expectedRevision:draft.revision}));assert.equal(checked.ready,true);assert.equal(store.read(draft.id).scenes[0].sourceDurationSeconds,undefined,'Measured check is read-only')
 await runtime.openPanel('video-studio');app.focus({steal:true});host.focus();studio=webContents.getAllWebContents().find(contents=>contents.getURL().endsWith('/studio.html'))!;await wait(()=>js("document.getElementById('scene-title').value.includes('原声')"),'Initial draft')
 await js("document.getElementById('view-toggle').click();true");await wait(()=>js("document.body.dataset.view==='advanced'"),'Opt into advanced video controls');await js("document.querySelector('[data-stage=\"4\"]').click();true");await wait(()=>js("!document.getElementById('seek').disabled"),'Initial preview');await js("document.querySelector('[data-inspector=captions]').click();document.getElementById('caption-panel').open=true;true")
 await js("document.getElementById('source-speech-segment').value='1';true");await click('source-speech-recognize');await wait(async()=>Boolean(store.read(draft.id).scenes[0].sourceSpeech),'Real Whisper base recognition');await wait(()=>js("!!document.getElementById('source-speech-heard')&&!document.getElementById('source-speech-recognize').disabled"),'Visible recognition rows');draft=store.read(draft.id);assert.equal(draft.scenes[0].captions![0].text,'Independent retained')
 await js("document.getElementById('source-speech-editor').scrollIntoView({block:'center'});true");fs.writeFileSync(path.join(proof,'studio-original-editor.png'),(await captureRendererEvidence(studio)).toPNG());
 const read=mediaRecord(await execute({operation:'read-source-speech',draftId:draft.id,expectedRevision:draft.revision,sceneId:'original'})),evidence=assertSpeechEvidence(read.evidence);assert.equal(evidence.language,'auto');assert.equal(JSON.parse(fs.readFileSync(path.join(artifacts,evidence.rawArtifactId),'utf8')).result.language,'en');assert.ok(evidence.segments.length);fs.copyFileSync(path.join(artifacts,evidence.rawArtifactId),path.join(proof,'source-whisper-raw.json'));fs.writeFileSync(path.join(proof,'source-evidence.json'),JSON.stringify(evidence,null,2)+'\n')
 await js("document.getElementById('source-speech-segment').value='0';document.getElementById('source-speech-segment').dispatchEvent(new Event('change',{bubbles:true}));true");await click('source-speech-read');await wait(()=>js("document.getElementById('source-speech-segment').value==='1'"),'Read restores recognized segment');await click('source-speech-listen');await wait(()=>js("document.querySelector('#source-speech-editor video')?.readyState>=1"),'Original source listening');assert.equal(await js("document.querySelector('#source-speech-editor video').dataset.artifactId"),sourceArtifactId);await js("document.querySelector('#source-speech-editor video').play()");await wait(()=>js("document.querySelector('#source-speech-editor video').currentTime>.1"),'Original audio advances');await js("document.querySelector('#source-speech-editor video').pause();true")
 await click('source-speech-apply');await wait(()=>js("document.getElementById('status').textContent.includes('试听并确认')"),'Listening confirmation required');assert.equal(store.read(draft.id).revision,draft.revision)
 await js("(()=>{const n=document.querySelector('#source-speech-editor textarea');n.value='Unsaved correction preserved';n.dispatchEvent(new Event('input',{bubbles:true}));return true})()");const concurrent=store.read(draft.id);concurrent.scenes[0].title+=' · external edit';await execute({operation:'update',draftId:concurrent.id,expectedRevision:concurrent.revision,draft:concurrent});await wait(()=>js("document.getElementById('status').textContent.includes('外部更新')"),'Unsaved source rows preserved across external change');assert.equal(await js("document.querySelector('#source-speech-editor textarea').value"),'Unsaved correction preserved');await js("document.getElementById('source-speech-heard').checked=true;true");await click('source-speech-apply');await wait(()=>js("document.getElementById('status').textContent.includes('STUDIO_CONFLICT')"),'Source review CAS conflict');assert.equal(await js("document.querySelector('#source-speech-editor textarea').value"),'Unsaved correction preserved');await js("window.confirm=()=>true;true");await click('reload');await wait(()=>js("!document.getElementById('source-speech-read').disabled"),'Explicit reload');await click('source-speech-read');await wait(()=>js("!!document.getElementById('source-speech-heard')"),'Reload original evidence')
 // Automated review fixture establishes GUI state/provenance, not human transcription accuracy.
 await js("(()=>{const row=document.querySelector('#source-speech-editor .caption-row');const inputs=row.querySelectorAll('input');inputs[0].value='0';inputs[1].value='3';row.querySelector('textarea').value='Artificial intelligence becomes super intelligence.';row.querySelector('textarea').dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('source-speech-heard').checked=true;return true})()")
 // Keep only the first corrected cue to avoid overlapping raw segments after changing its endpoint.
 const rows=await js<number>("document.querySelectorAll('#source-speech-editor .caption-row').length");if(rows>1){await js("(()=>{const rows=[...document.querySelectorAll('#source-speech-editor .caption-row')];for(let i=1;i<rows.length;i++){const inputs=rows[i].querySelectorAll('input');inputs[0].value=String(3+(i-1)*.02);inputs[1].value=String(3+i*.02)}return true})()")}
 await click('source-speech-apply');await wait(async()=>Boolean(store.read(draft.id).scenes[0].sourceCaptionBinding),'Reviewed source cues saved');await wait(()=>js("!!document.getElementById('caption-translation-0')&&!document.getElementById('caption-translation-0').disabled"),'Separate translation field');draft=store.read(draft.id);assert.equal(draft.scenes[0].audioArtifactId,undefined);assert.equal(draft.scenes[0].sourceCaptionBinding!.origin,'user-edited')
 await js("(()=>{const n=document.getElementById('caption-translation-0');n.value='人工智能将走向超级智能。';n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}));return true})()");await wait(async()=>store.read(draft.id).scenes[0].captions![0].translationOrigin==='user-edited','Manual translation saved');await wait(()=>js("!document.getElementById('caption-translate').disabled"),'Translation settled');await click('caption-translate');await wait(async()=>prompts.length===1,'Translation routes to owning Assistant');assert.ok(prompts[0].includes('set-caption-translations'))
 draft=store.read(draft.id);const translated=mediaRecord(await execute({operation:'set-caption-translations',draftId:draft.id,expectedRevision:draft.revision,sceneId:'original',translations:[{cueIndex:0,originalText:draft.scenes[0].captions![0].text,translationText:'模型重译不覆盖人工'}]}));assert.deepEqual(translated.skippedCueIndices,[0]);draft=store.read(draft.id)
 for(const format of ['srt','vtt']){const result=mediaRecord(await execute({operation:'export-captions',draftId:draft.id,expectedRevision:draft.revision,captionFormat:format}));const text=fs.readFileSync(path.join(artifacts,String(result.artifactId)),'utf8');assert.ok(text.includes('Artificial intelligence'));assert.ok(text.includes('人工智能'));assert.equal(result.sentenceTiming,'edited-source-cues');fs.copyFileSync(path.join(artifacts,String(result.artifactId)),path.join(proof,'bilingual.'+format))}
 await click('preview-refresh');await wait(()=>js("!document.getElementById('seek').disabled"),'Bilingual preview');await js("document.getElementById('seek').value='5';document.getElementById('seek').dispatchEvent(new Event('input',{bubbles:true}));true");await wait(()=>js("document.getElementById('scene-title').value==='三点总结'"),'Summary inspector follows timeline');await click('preview-refresh');await wait(()=>js("!document.getElementById('seek').disabled"),'Refresh settled');assert.equal(await js("Number(document.getElementById('seek').value)"),5);assert.equal(await js("document.getElementById('scene-title').value"),'三点总结')
 await js("document.querySelector('[data-inspector=visual]').click();true");await wait(()=>js("document.getElementById('scene-template').value==='summary'"),'Template inspector');await js("(()=>{const n=document.getElementById('template-accent');n.value='#ffbb44';n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}));return true})()");await wait(async()=>store.read(draft.id).scenes[1].sceneTemplate?.accentColor==='#ffbb44','Template color persists');await click('undo');await wait(async()=>store.read(draft.id).scenes[1].sceneTemplate?.accentColor!=='#ffbb44','Template undo');await click('redo');await wait(async()=>store.read(draft.id).scenes[1].sceneTemplate?.accentColor==='#ffbb44','Template redo')
 await click('delivery-open');await click('studio-review-capture');await wait(()=>js("document.querySelectorAll('#studio-review-frames img').length===4"),'Key-frame gallery');await js("document.getElementById('studio-review-frames').scrollIntoView({block:'center'});true");fs.writeFileSync(path.join(proof,'studio-next-review.png'),(await captureRendererEvidence(studio)).toPNG())
 const comparisons:{ratio:string;errors:number[]}[]=[]
 for(const dimensions of [[640,360],[540,720]] as const){draft=store.read(draft.id);draft.width=dimensions[0];draft.height=dimensions[1];draft=await execute({operation:'update',draftId:draft.id,expectedRevision:draft.revision,draft}) as VideoDraft;const result=mediaRecord(await execute({operation:'render',draftId:draft.id,expectedRevision:draft.revision})),exported=mediaRecord(result.export);await wait(()=>js(`document.getElementById('studio-output-current').textContent.includes('${dimensions[0]} × ${dimensions[1]}')`),'Updated parameters');await click('preview-refresh');await wait(()=>js(`document.getElementById('preview').width===${dimensions[0]}&&!document.getElementById('seek').disabled`),'Parity preview ready');const output=String(exported.artifactId);fs.copyFileSync(path.join(artifacts,output),path.join(proof,`studio-next-${dimensions[0]}x${dimensions[1]}.mp4`));const bytes=fs.readFileSync(path.join(artifacts,output)).toString('base64');const errors:number[]=[]
  for(const time of [1,5,7,9]){await js(`document.getElementById('seek').value='${time}';document.getElementById('seek').dispatchEvent(new Event('input',{bubbles:true}));true`);await wait(()=>js(`Math.abs(Number(document.getElementById('seek').value)-${time})<.01`),'Parity time');const difference=await js<number>(`(async()=>{const v=document.createElement('video');v.muted=true;v.src=URL.createObjectURL(new Blob([Uint8Array.from(atob(${JSON.stringify(bytes)}),c=>c.charCodeAt(0))],{type:'video/mp4'}));document.body.append(v);await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=reject});const decoded=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('MP4 frame timeout')),8000);v.requestVideoFrameCallback(()=>{clearTimeout(timer);resolve()})});v.currentTime=${time};await v.play();await decoded;v.pause();const p=document.getElementById('preview'),c=document.createElement('canvas');c.width=p.width;c.height=p.height;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data,b=p.getContext('2d').getImageData(0,0,p.width,p.height).data;let sum=0;for(let i=0;i<a.length;i+=4)sum+=Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2]);URL.revokeObjectURL(v.src);v.remove();return sum/(a.length/4*3)})()`);assert.ok(difference<12,'Native MP4/preview parity: '+difference);errors.push(difference);const png=await js<string>("document.getElementById('preview').toDataURL('image/png').split(',')[1]");fs.writeFileSync(path.join(proof,`frame-${dimensions[0]}-${time}.png`),Buffer.from(png,'base64'))}
  comparisons.push({ratio:dimensions.join('x'),errors})
 }
 draft=store.read(draft.id);const existing=new Set(fs.readdirSync(artifacts));draft.scenes[1].captions=[{startSeconds:0,endSeconds:1.5,text:'字幕'.repeat(100),translationText:'translated '.repeat(18)}];draft=await execute({operation:'update',draftId:draft.id,expectedRevision:draft.revision,draft}) as VideoDraft;await assert.rejects(execute({operation:'render',draftId:draft.id,expectedRevision:draft.revision}),/STUDIO_TEXT_LAYOUT/);assert.deepEqual(fs.readdirSync(artifacts).filter(id=>!existing.has(id)),[],'Layout failure leaves no new completed outputs')
 fs.writeFileSync(path.join(proof,'verification.json'),JSON.stringify({status:'passed',source:process.env.BMW_STUDIO_SOURCE?'copied public interview':'synthetic English local-TTS video',humanTranscriptionAccuracy:false,paidTranslationModel:false,comparisons,draft:store.read(draft.id)},null,2)+'\n');console.log('PASS original video Whisper base, listening/correction, CAS/user translation retention, refresh/inspector, template undo, key-frame review, bilingual SRT/VTT and portrait/landscape native parity',comparisons)
}catch(error){exitCode=1;console.error('Studio next failed in '+phase,error)}finally{clearTimeout(timeout);try{if(runtime)await runtime.stop();media?.window?.destroy();if(host&&!host.isDestroyed())host.destroy()}catch(error){console.error(error);exitCode=1}fs.rmSync(temporary,{recursive:true,force:true});app.exit(exitCode)}}
void run()
