import type {ModuleId} from './module-catalog.js'
export type TestLayer = 'unit' | 'contract' | 'boundary' | 'integration' | 'desktop' | 'media' | 'external' | 'type'
export interface TestDefinition {
  id: string; file: string; layer: TestLayer; modules: readonly ModuleId[]
  runner: 'node-test' | 'node' | 'electron' | 'desktop' | 'type'
  watch?: readonly string[]
  group?: 'workspace' | 'projects' | 'settings' | 'native'
  env?: Readonly<Record<string,string>>
  optIn?: string
}
function node(id:string,file:string,layer:TestLayer,module:ModuleId,watch?:readonly string[]):TestDefinition {
  return {id,file,layer,modules:[module],runner:'node-test',watch}
}
const p='packages/'
export const tests: readonly TestDefinition[] = [
  node('agent.context',p+'agent-contract/test/context-sync.test.ts','contract','agent-contract'),
  ...(['browser-schema','mcp-tool-catalog','session-operations','bridge-shutdown','browser-deadline','screenshot-read','renderer-read','media-artifact','tab-policy'] as const).map((name,index)=>node(['browser.schema','browser.catalog','browser.operations','browser.shutdown','browser.deadline','browser.screenshot','browser.renderer-read','browser.download','browser.tab-policy'][index],p+'browser-capability/test/'+name+'.test.ts',index<5?'contract':'unit','browser-capability')),
  node('browser.host-contract',p+'browser-capability/test/browser-host.test.ts','contract','browser-capability'),
  ...(['dsh-runtime','dsh-transport','dsh-preset','harness-port','dsh-context','browser-failure-guard','workspace-context','video-case-log'] as const).map(name=>node('dsh.'+name,p+'harness-dsh/test/'+name+'.test.ts',name==='browser-failure-guard'||name==='video-case-log'?'unit':'contract','harness-dsh')),
  ...(['media-controller','media-processing','video-production','video-options'] as const).map((name,index)=>node(['media.controller','media.processing','media.production','media.options'][index],p+'media-native/test/'+name+'.test.ts',index===3?'unit':'contract','media-native')),
  node('media.port-contract',p+'media-native/test/media-port.test.ts','contract','media-native'),
  ...(['project-store','global-settings-store','scheduled-task-store','state-load','layout-store','layout-docking','permission-policy','menu-policy','restart-policy','session-continuity','browser-user-agent','project-panel-layering','driver-boundary','bmw-catalog','product-boundaries','remote-control-boundary'] as const).map((name,index)=>node(['platform.projects','platform.settings','platform.schedules','platform.state','platform.layout','platform.docking','platform.permissions','platform.menu','platform.restart','platform.continuity','platform.user-agent','platform.project-panel','platform.driver-binding','platform.catalog','platform.boundaries','platform.remote-boundary'][index],p+'platform/test/'+name+'.test.ts',index>=13?'boundary':index===12||index===3||index===9?'contract':'unit','platform',name==='project-panel-layering'?['packages/platform/src/main.ts','packages/platform/src/renderer/']:undefined)),
  node('platform.shell-ipc',p+'platform/test/shell-ipc.test.ts','contract','platform'),
  node('platform.permission-store',p+'platform/test/permission-store.test.ts','contract','platform'),
  node('platform.continuity-state',p+'platform/test/continuity-state.test.ts','contract','platform'),
  node('platform.feature-contract',p+'platform/test/feature-contract.test.ts','contract','platform'),
  ...(['studio-materials','video-studio','video-settings','video-boundary'] as const).map((name,index)=>node(['video.materials','video.studio','video.settings','video.boundary'][index],p+'feature-video/test/'+name+'.test.ts',index===3?'boundary':index===0?'unit':'contract','feature-video')),
  node('architecture.boundaries','scripts/test/module-boundary.test.ts','boundary','validation'),
  node('validation.selection','scripts/test/test-selection.test.ts','unit','validation',['scripts/module-catalog.ts','scripts/test-catalog.ts','scripts/source-graph.ts','scripts/test-selection.ts','scripts/test-runner.ts']),
  {id:'api.types',file:'scripts/test/public-interfaces.type-test.ts',layer:'type',modules:['validation','platform','agent-contract','browser-capability','media-native','feature-video'],runner:'type',watch:['packages/agent-contract/index.ts','packages/browser-capability/src/browser-host.ts','packages/browser-capability/src/browser-schema.ts','packages/platform/src/feature-contract.ts','packages/platform/src/product-definition.ts','packages/media-native/src/media-port.ts']},
  {id:'driver',file:'scripts/agent-driver-smoke.ts',layer:'integration',modules:['platform','agent-contract','browser-capability'],runner:'electron',watch:['packages/platform/src/shell-ipc.ts','packages/platform/src/preload/shell-preload.cts','packages/platform/src/permission-store.ts','packages/platform/src/main.ts','packages/platform/src/project-store.ts','packages/platform/src/feature-contract.ts','packages/agent-contract/','packages/browser-capability/src/bridge-server.ts','packages/browser-capability/src/browser-mcp-server.ts','scripts/fixture-browser-client.ts','packages/browser-capability/src/browser-schema.ts','packages/browser-capability/src/tool-catalog.ts','packages/browser-capability/src/browser-host.ts','packages/browser-capability/src/browser-kernel.ts']},
  {id:'startup-recovery',file:'scripts/state-load-smoke.ts',layer:'integration',modules:['platform'],runner:'electron',env:{BMW_STATE_STARTUP_SCENARIO:'retry'},watch:['packages/platform/src/layout-store.ts','packages/platform/src/permission-store.ts','packages/platform/src/session-continuity.ts','packages/platform/src/main.ts','packages/platform/src/state-load.ts','packages/platform/src/project-store.ts','packages/platform/src/global-settings-store.ts','packages/platform/src/scheduled-task-store.ts']},
  {id:'startup-exit',file:'scripts/state-load-smoke.ts',layer:'integration',modules:['platform'],runner:'electron',env:{BMW_STATE_STARTUP_SCENARIO:'exit'},watch:['packages/platform/src/layout-store.ts','packages/platform/src/permission-store.ts','packages/platform/src/session-continuity.ts','packages/platform/src/main.ts','packages/platform/src/state-load.ts','packages/platform/src/project-store.ts','packages/platform/src/global-settings-store.ts','packages/platform/src/scheduled-task-store.ts']},
  ...(['permissions','layout','continuity-config','continuity-snapshot'] as const).flatMap(kind=>(['retry','exit'] as const).map(scenario=>({id:'startup.'+kind+'.'+scenario,file:'scripts/state-load-smoke.ts',layer:'integration' as const,modules:['platform'] as const,runner:'electron' as const,env:{BMW_STATE_STARTUP_KIND:kind,BMW_STATE_STARTUP_SCENARIO:scenario},watch:['packages/platform/src/main.ts','packages/platform/src/state-load.ts','packages/platform/src/project-store.ts','packages/platform/src/global-settings-store.ts','packages/platform/src/scheduled-task-store.ts','packages/platform/src/layout-store.ts','packages/platform/src/permission-store.ts','packages/platform/src/session-continuity.ts']}))),
  {id:'dsh',file:'scripts/dsh-compatibility-smoke.ts',layer:'integration',modules:['harness-dsh','agent-contract'],runner:'node'},
  ...(['workspace','projects','settings','native'] as const).map(group=>({id:'desktop.'+group,file:'scripts/desktop-smoke.ts',layer:'desktop' as const,runner:'desktop' as const,group,modules:['platform','harness-dsh','browser-capability','feature-video'] as const,watch:[
    'scripts/desktop-suite.ts','packages/platform/src/main.ts','packages/platform/src/preload/','packages/platform/src/renderer/shell.html','packages/platform/src/renderer/shell.css',
    ...(group==='workspace'?['packages/platform/src/feature-contract.ts','packages/feature-video/src/studio-runtime.ts','packages/feature-video/src/renderer/studio.html','packages/browser-capability/src/browser-host.ts']:[]),
    ...(group==='projects'?['packages/platform/src/project-store.ts','packages/agent-contract/','packages/harness-dsh/src/dsh-client.ts','packages/harness-dsh/src/dsh-context.ts','packages/browser-capability/src/browser-kernel.ts','packages/browser-capability/src/tab-policy.ts']:[]),
    ...(group==='settings'?['packages/platform/src/global-settings-store.ts','packages/platform/src/layout-store.ts','packages/media-native/src/video-options','packages/feature-video/src/video-settings.ts']:[]),
    ...(group==='native'?['packages/platform/src/layout','packages/platform/src/menu-policy.ts','packages/platform/src/project-store.ts','packages/harness-dsh/preload/']:[]),
    'packages/platform/src/renderer/shell.ts'
  ]})),
  {id:'studio',file:'scripts/video-studio-smoke.ts',layer:'integration',modules:['feature-video','media-native'],runner:'electron',watch:['packages/media-native/src/image-contract.ts','packages/media-native/src/media/image-decoder.ts','packages/media-native/src/visual-segments.ts','packages/media-native/src/caption-export.ts','packages/media-native/src/text-export.ts','packages/media-native/src/media-contract.ts','packages/media-native/src/media/processing.ts','packages/media-native/src/media-processor.ts','packages/media-native/src/media-controller.ts','packages/feature-video/','packages/browser-capability/src/browser-host.ts','packages/platform/src/feature-contract.ts','packages/media-native/src/media-port.ts','packages/media-native/src/video-options','packages/media-native/src/composition-contract.ts','packages/media-native/src/media/composition-paint.ts','packages/media-native/src/media/composition-audio.ts','packages/media-native/src/media/linear-frames.ts']},
  {id:'browser.background',file:'scripts/browser-background-smoke.ts',layer:'integration',modules:['browser-capability'],runner:'electron',watch:['packages/browser-capability/src/browser-kernel.ts','packages/browser-capability/src/renderer-read.ts','packages/browser-capability/src/screenshot-read.ts','packages/browser-capability/src/media-artifact.ts','packages/browser-capability/src/bridge-server.ts']},
  {id:'media.capture',file:'scripts/media-capture-smoke.ts',layer:'media',modules:['media-native','browser-capability'],runner:'electron',watch:['packages/media-native/src/media-controller.ts','packages/media-native/src/capture-policy.ts','packages/media-native/src/media/media.','packages/media-native/src/preload/media-preload.cts','packages/browser-capability/src/browser-kernel.ts']},
  {id:'media.processing-runtime',file:'scripts/media-processing-smoke.ts',layer:'media',modules:['media-native'],runner:'electron',watch:['packages/browser-capability/src/browser-schema.ts','packages/browser-capability/src/browser-capability-registry.ts','packages/browser-capability/src/browser-kernel.ts','packages/browser-capability/src/bridge-server.ts','packages/media-native/src/image-drawing-contract.ts','packages/media-native/src/media/image-drawing.ts','packages/media-native/src/image-contract.ts','packages/media-native/src/media/image-decoder.ts','packages/media-native/src/media-processor.ts','packages/media-native/src/media-controller.ts','packages/media-native/src/media-contract.ts','packages/media-native/src/artifact-job-io.ts','packages/media-native/src/media/processing.','packages/media-native/src/media/linear-frames.ts','packages/media-native/src/preload/processing-preload.cts']},
  {id:'video',file:'scripts/video-production-smoke.ts',layer:'media',modules:['media-native','feature-video'],runner:'electron',watch:['packages/media-native/src/image-contract.ts','packages/media-native/src/media/image-decoder.ts','packages/media-native/src/visual-segments.ts','packages/media-native/src/text-export.ts','packages/media-native/src/media-contract.ts','packages/media-native/src/composition','packages/media-native/src/media/composition','packages/media-native/src/source-audio.ts','packages/media-native/src/artifact-job-io.ts','packages/media-native/src/video-options.ts','packages/media-native/src/media-port.ts','packages/media-native/src/media-controller.ts','packages/media-native/src/preload/composition-preload.cts','packages/feature-video/index.ts','packages/feature-video/src/video-settings.ts']},
  {id:'localNarration',file:'scripts/narration-smoke.ts',env:{BMW_TTS_TEST_PROVIDER:'local-matcha'},layer:'media',modules:['media-native'],runner:'electron',watch:['packages/media-native/src/image-contract.ts','packages/media-native/src/media-contract.ts','packages/media-native/src/narration','packages/media-native/src/local-tts-assets.ts','packages/media-native/src/media/narration','packages/media-native/src/media-controller.ts','packages/media-native/src/media-port.ts','packages/media-native/src/preload/narration-preload.cts','scripts/install-local-tts.ts']},
  {id:'external.vision',file:'scripts/vision-model-smoke.ts',layer:'external',modules:['browser-capability','harness-dsh'],runner:'electron',optIn:'BMW_VISION_TEST=1'},
  {id:'external.edge',file:'scripts/narration-smoke.ts',layer:'external',modules:['media-native'],runner:'electron',env:{BMW_TTS_TEST_PROVIDER:'edge'},optIn:'BMW_TTS_TEST_PROVIDER=edge'}
]
